
[platformio]

src_dir = examples/blink
; src_dir = examples/can_advanced
; src_dir = examples/can_basic_echo
; src_dir = examples/can_dual_basic_echo
; src_dir = examples/can_dual_speed_test
; src_dir = examples/can_rs485_dual_echo_back
; src_dir = examples/can_speed_test
; src_dir = examples/rs485_basic_echo
; src_dir = examples/rs485_dual_basic_echo
; src_dir = examples/rs485_dual_driver_speed_test
; src_dir = examples/rs485_dual_speed_test
; src_dir = examples/rs485_modbus_module
; src_dir = examples/rs485_speed_test
; src_dir = examples/wifi_scan

boards_dir = board


[env:t-c5-base]
board  = t-c5-base
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
upload_speed =  921600
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=1
monitor_filters =
	default
	esp32_exception_decoder
    time
